version: '3.6'
services:

  calories-api:
    build:
      context: .
      args:
        ENVIRONMENT: dev
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "${API_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mariadb
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - /pegasus/calories:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TZ=${MYSQL_TZ}
  docs:
    image: swaggerapi/swagger-ui
    ports:
      - '${SWAGGER_PORT}:8080'
    environment:
      - SWAGGER_JSON=/app/swagger.json
    volumes:
      - ./swagger.json:/app/swagger.json
